// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdsUIClient is the client API for IdsUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdsUIClient interface {
	// ListEngineSpecs returns a list of Intrusion Detection Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (IdsUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type idsUIClient struct {
	cc grpc.ClientConnInterface
}

func NewIdsUIClient(cc grpc.ClientConnInterface) IdsUIClient {
	return &idsUIClient{cc}
}

func (c *idsUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (IdsUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &IdsUI_ServiceDesc.Streams[0], "/v1.IdsUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &idsUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IdsUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type idsUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *idsUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *idsUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.IdsUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdsUIServer is the server API for IdsUI service.
// All implementations must embed UnimplementedIdsUIServer
// for forward compatibility
type IdsUIServer interface {
	// ListEngineSpecs returns a list of Intrusion Detection Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, IdsUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedIdsUIServer()
}

// UnimplementedIdsUIServer must be embedded to have forward compatible implementations.
type UnimplementedIdsUIServer struct {
}

func (UnimplementedIdsUIServer) ListEngineSpecs(*ListEngineSpecsRequest, IdsUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedIdsUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedIdsUIServer) mustEmbedUnimplementedIdsUIServer() {}

// UnsafeIdsUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdsUIServer will
// result in compilation errors.
type UnsafeIdsUIServer interface {
	mustEmbedUnimplementedIdsUIServer()
}

func RegisterIdsUIServer(s grpc.ServiceRegistrar, srv IdsUIServer) {
	s.RegisterService(&IdsUI_ServiceDesc, srv)
}

func _IdsUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IdsUIServer).ListEngineSpecs(m, &idsUIListEngineSpecsServer{stream})
}

type IdsUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type idsUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *idsUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _IdsUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdsUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.IdsUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdsUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdsUI_ServiceDesc is the grpc.ServiceDesc for IdsUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdsUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.IdsUI",
	HandlerType: (*IdsUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _IdsUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _IdsUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ids-ui.proto",
}
